# Generated by Django 2.1.5 on 2019-04-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_serveruser_require_trailing_slash'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveruser',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
